#:schema node_modules/wrangler/config-schema.json
name = "ddns-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-11-15"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
[observability]
enabled = true


# Variable bindings
[vars]
#APPLICATION_TOKEN = "FeMxJH7yu39UU696GyDx3yS6DT7Mv6nwOqVEyIBs"
